# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf9d39620405ba13c23c4d37e775998004d8f155f88cec31a8db03306e78a06daa43421ac6e7ac48b02ffd9c34a72e6cab84ed5d9e273c42689386c3f41767a

test:
  secret_key_base: 47c86beac55c2bf647e9d50c354465d7b096d3054354d1187625b72afe909091d97c3fa6dd196f326e690876c9440fe7f1ae89e51f107297fb899c955eec4a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
